### ISSUE TITLE
[Bug] Color codes for weapon not working

### ISSUE THREAD

**Issue by ghost** [sb2bg/CustomDeathMessages#12]
&7[&b%kill-weapon%&7] - on default same

**Comment by sb2bg** [comment]
I'm not 100% sure what you mean, but heres what I can tell you:

When 'enable-item-on-hover' is enabled, any color code (e.g. '&b') will be overridden by how the item looks in the player inventory. If the item has a white name, the item will appear white in chat, no matter what. However, if it is disabled, white items, or items without colored names, will adopt the color code from the message. 

This is expected behavior, not a bug. I am going to close this issue, however, if you still think it's a bug/something else is going on, you are more than welcome to open another issue with more details.

**Comment by ghost** [comment]
:(
in deathmessage , you can

**Comment by sb2bg** [comment]
you can what?

**Comment by ghost** [comment]
> you can what?
i mean message 'you killed with &6diamond sword. for example, it white

**Comment by ghost** [comment]
but on death message if i set &6 = it gold, normal what i need

**Comment by sb2bg** [comment]
I'm sorry but I don't understand what you mean. Can you try to use google translate? Or speak in your first language and I will translate?

**Comment by sb2bg** [comment]
Здесь вы можете говорить по-русски

**Comment by ghost** [comment]
> I'm not 100% sure what you mean, but heres what I can tell you:
> 
> When 'enable-item-on-hover' is enabled, any color code (e.g. '&b') will be overridden by how the item looks in the player inventory. If the item has a white name, the item will appear white in chat, no matter what. However, if it is disabled, white items, or items without colored names, will adopt the color code from the message.
> 
> This is expected behavior, not a bug. I am going to close this issue, however, if you still think it's a bug/something else is going on, you are more than welcome to open another issue with more details.

вы правы, но хотелось бы видеть чтобы тоже было цветным.

**Comment by sb2bg** [comment]
Я не уверен, возможно ли это из-за природы того, как он запрограммирован. Я сделаю все возможное, чтобы увидеть, если я могу.

**Comment by ghost** [comment]
> Я не уверен, возможно ли это из-за природы того, как он запрограммирован. Я сделаю все возможное, чтобы увидеть, если я могу.

working on deathmessages, not big problem dont worry
